name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 8
          - 10
          - 12
          - 14
        include:
          - os: windows-latest
            node_version: 14
          - os: macos-latest
            node_version: 14
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g .
        npx instant-markdown-d --version
        npm test &
        sleep 5
        npm stop
      env:
        CI: true
